version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRES_IN_HOURS=24
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./src/frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

  # Optional: Add database for production
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: teamsync
  #     POSTGRES_USER: teamsync
  #     POSTGRES_PASSWORD: your-secure-password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
